version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      steps:
      - browser-tools/install-browser-tools:
          firefox-version: 80.0.1
      - cypress/run:
          cypress-command: 'npx cypress run --browser firefox'