version: 2.1

jobs:
  run1:
    docker:
      - image: cypress/base:16.14.2-slim
    steps:
      - checkout
      - run: 
          command: npm install cypress --save-dev
      - run: 
          command: npm run test1

  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run lint
workflows:
  build_and_test:
    jobs:
      - lint
      - run1
