version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypressssssqqq/runnnnnnnn:
          install-browsers: true
          cypress-command: 'npx cypress run --browser firefox'
          parallelism: 4