version: 2.1

jobs:
  run1:
    docker:
      - image: cypress/base:16.14.2-slim
    steps:
      - checkout
      - run: apk add --update openssh-client git
      - run: 
          command: npm install cypress --save-dev
      - run: 
          command: npm run test1
workflows:
  build_and_test:
    jobs:
      - run1
